### ISSUE TITLE
Slows down iphoneX

### ISSUE THREAD

**Issue by jemilox** [browniefed/react-native-ticker#10]
Was using this until we noticed huge lag problems on only the iphoneX.

Narrowed it down to this library. Not completely sure what the issue was, but removing it for now.

**Comment by browniefed** [comment]
Thanks, I'd be curious if you could share an example of the string you were attempting to tick?

**Comment by jemilox** [comment]
They were integers between 0-1000

**Comment by browniefed** [comment]
Sorry, should have clarified more. Were you rendering a lot of these? What was the situation where you were seeing slowness.

**Comment by jemilox** [comment]
Nope, we were rending once every like 5 seconds at the fastest. The rest of
our app would get really slow. It was affecting everything. As soon as I
cut out the ticker, everything stopped lagging.  I checked for number of
renders on my component that was using it, and it only rendered once.  It
worked just find on android and lower versions of iphone, which was really
weird.

**Comment by browniefed** [comment]
Are you sure you didn't turn on slow animations?

**Comment by browniefed** [comment]
I believe you can toggle with cmd + shift + t, and or with the simulator open you can toggle it from the debug menu.

**Comment by jemilox** [comment]
I am positive :(

It was happening when we deployed to real phones too.  It is possible this
is due to something else, however, I narrowed it down to the actual
component.

**Comment by gilberger** [comment]
I've been experiencing the same issue.

Seems to be something with the handleMeasure function, triggered by onLayout prop of the container View.
the solution I found was to verify that this.state.measured is false before updating the height of the layout.

also added a PR for that https://github.com/browniefed/react-native-ticker/pull/11

**Comment by browniefed** [comment]
v2.20 has been released.

**Comment by jemilox** [comment]
yay! Thanks!

**Comment by slorber** [comment]
Hi,

I can confirm the slowness on iOS. 
We noticed this on some iphone XS, which was surprising because the app did fine with older iphones. 

It has been reported with an iphone 7 also.

I have not been able to reproduce this on my own ios hardware devices (older)

It seems @gilberger solution fixes the problem, but a bug remains due to react's event pooling. We must call e.persist() because when using setState with an update function (like it is now) there's no guarantee that this fn will be called in same batch and in my case it lead to errors.

PR with a simple fix here: https://github.com/browniefed/react-native-ticker/pull/13
